name: client
description: An e-commerce Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  sqflite: ^2.3.3
  app_links: ^6.0.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.0.0  # Added for in-app web view fallback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true